name: Latest Medium articles workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-readme-with-articles:
    name: "Update this repo's README with latest blog posts"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull the articles from Medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@dariovarrialeapps"
          committer_username: "dariowskii"
          committer_email: "dariovarriale@rocketmail.com"
          commit_message: "Updated Medium articles in README 🚀"
          date_format: "ddd, mmm dd yyyy - HH:MM"
          categories_template: '<code>#$category</code> '
          template: '$newline - $randomEmoji(💯,🔥,💫,🚀,🌮) [$title]($url) ![Static Badge](https://img.shields.io/badge/Medium-post?logo=medium&logoColor=%23fff&color=%23000) <br/> <i>$date</i> <br/> $categories <br/>'
