name: Latest Medium articles workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-readme-with-articles:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull the articles from Medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://medium.com/feed/@dariovarrialeapps'
          template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮)[$title]($url) $newline - $description $newline"
